# Cloud Build configuration for chat service
steps:
  # Run tests BEFORE everything else (blocks deployment if tests fail)
  - name: "golang:1.21"
    dir: "chat-server"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "Running tests..."

        # Install minimock
        go install github.com/gojuno/minimock/v3/cmd/minimock@latest

        # Generate mocks
        make generate-mocks

        # Run all tests
        make test

        echo "✅ All tests passed!"

  # Run database migrations BEFORE deployment
  - name: "alpine:3.18"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        # Install dependencies
        apk add --no-cache wget postgresql-client

        # Download goose
        wget -O /workspace/goose https://github.com/pressly/goose/releases/download/v3.14.0/goose_linux_x86_64
        chmod +x /workspace/goose

        # Run migrations
        cd chat-server/migrations
        /workspace/goose postgres "$$CHAT_DATABASE_URL" up -v
    secretEnv: ['CHAT_DATABASE_URL']

  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/go-chats/chat-service:$COMMIT_SHA"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/go-chats/chat-service:latest"
      - "."
    dir: "chat-server"

  # Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/go-chats/chat-service"

  # Deploy to Cloud Run with database URL secret
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "chat-service"
      - "--image=us-central1-docker.pkg.dev/$PROJECT_ID/go-chats/chat-service:$COMMIT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--use-http2"
      - "--set-secrets=PG_DSN=chat-database-url:latest"

availableSecrets:
  secretManager:
    - versionName: projects/go-chats-478611/secrets/chat-database-url/versions/latest
      env: 'CHAT_DATABASE_URL'

# Store images in Artifact Registry
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/go-chats/chat-service:$COMMIT_SHA"
  - "us-central1-docker.pkg.dev/$PROJECT_ID/go-chats/chat-service:latest"

options:
  logging: CLOUD_LOGGING_ONLY
