# Cloud Build configuration for chat service
steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/go-chats/chat-service:$COMMIT_SHA"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/go-chats/chat-service:latest"
      - "."
    dir: "chat-server"

  # Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/go-chats/chat-service"

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "chat-service"
      - "--image=us-central1-docker.pkg.dev/$PROJECT_ID/go-chats/chat-service:$COMMIT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--use-http2"

# Store images in Artifact Registry
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/go-chats/chat-service:$COMMIT_SHA"
  - "us-central1-docker.pkg.dev/$PROJECT_ID/go-chats/chat-service:latest"

options:
  logging: CLOUD_LOGGING_ONLY
